platform :ios, '12.0'

target 'CoreModule_Example' do
  use_frameworks!
  pod 'CoreModule', :path => '../'
  pod 'Alamofire', '4.9.0'
#  pod 'JGProgressHUD'
#  pod 'IQKeyboardManagerSwift'
#  pod 'Kingfisher'
#  pod 'RxSwift'
#  pod 'RxCocoa'
#  pod 'RxAlamofire'
#  pod 'SwiftSoup'
#  pod 'MOLH'
#  pod 'JVFloatLabeledTextField'
#  pod 'CRRefresh'
#  pod 'FittedSheets'
#  pod 'ObjectMapper'
#  pod 'CryptoSwift'
#  pod 'netfox'
#  pod 'AnimatedCollectionViewLayout'
#  pod 'PopupDialog', '~> 1.1'
#  pod 'AzureNotificationHubs-iOS'
#  pod 'Expression'
#  pod 'SVGKit'
#  pod 'Toast-Swift', '5.0.1'

  target 'CoreModule_Tests' do
    # Pods for testing
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
##      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#    end
#  end
#end
