platform :ios, '12.0'

target 'CoreModule_Example' do
  use_frameworks!
  pod 'CoreModule', :path => '../'
  pod 'JGProgressHUD'#, '2.2'
  pod 'IQKeyboardManagerSwift', '6.5.6'
  pod 'Kingfisher'#, '7.0'
#  pod 'RxSwift'#, '~> 5'
#  pod 'RxCocoa', '~> 5'
#  pod 'RxAlamofire'
  pod 'SwiftSoup'
  pod 'MOLH'#, '0.8'
  pod 'JVFloatLabeledTextField'
  pod 'CRRefresh'#, '1.1.3'
  pod 'FittedSheets', '1.3.0'
  pod 'TransitionButton', '0.5.2'
#  pod 'lottie-ios', '2.5.3'
  pod 'ObjectMapper'#, '3.4.2'
  pod 'CryptoSwift'#, '~> 1.3.8'
  pod 'netfox', '1.20.0'
  pod 'AnimatedCollectionViewLayout'
#  pod "SCPageControl"
  pod 'AppCenter/Distribute'
  pod 'PopupDialog', '~> 1.1'
  pod 'DropDown'
  pod 'CalendarDateRangePicker'
  pod 'FSCalendar'
  pod 'AzureNotificationHubs-iOS'
  pod 'Expression'
  pod 'SVGKit'
  pod 'Toast-Swift', '5.0.1'
#  pod 'EzPopup'
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'InitialsImageView'
  pod 'AlignedCollectionViewFlowLayout'
  pod 'DRPLoadingSpinner'
  pod 'PhoneNumberKit', '~> 3.3'
# pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
  pod 'FirebaseCrashlytics'
  pod 'FirebasePerformance'
  pod 'BetterSegmentedControl' #, '~> 1.3'
  pod 'SkeletonView'
  pod 'DropDown'

  target 'CoreModule_Tests' do
    # Pods for testing
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
##      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#    end
#  end
#end
